### ISSUE TITLE
Core set battle maps grid is off

### ISSUE THREAD

**Issue by illotum** [Stefouch/t2k4e#60]
### Describe the Bug
Battle maps have their grid at 105px square, which doesn't match the scale nor the underlying hex grid.

### Severity
Low

### Context
The scenes from the Twilight 2k Core Set Module.

### To Reproduce
Version was acquired and downloaded today, Nov 16.

### Expected Behavior
Maps' grid settings match the artwork. For example,  on Americatown this is achieved by setting the grid to 315px Hexagonal - Odd.

### Screenshots
<img width="250" alt="Default scene grid" src="https://user-images.githubusercontent.com/1162134/142138471-e80b4670-1d39-419f-b1d6-b0e0fe81d1cd.png">

### Additional Context
N/A

**Comment by kylania** [comment]
I was able to get the Battlemap style maps to match grid with a 0.5 scale and a 250 pixel Hex Column - Odd setting.

Americatown and other Scenarios was 1.0 Scale and 315 pixel Hex Row - Odd.

Sweden map was pretty close with the Hex Column - Odd and 133 pixel, but needed to be bumped to -30 9 to match up better.
Poland looked best at -30 10

**Comment by Stefouch** [comment]
Hi @kylania !

Thanks for the comprehensive report.

Can you send a screenshot of what you obtained after your custom modifications ?

**Comment by kylania** [comment]
Hi, sorry for the background music, didn't realize it would be recording that!  But here's a walk through of the changes from first import:  

https://youtu.be/LEMv-SM3AWA

And here are comparison images of before and after for each map type:
Sweden:
![Map_Sweden_Default](https://user-images.githubusercontent.com/119372/142216027-1db7ab8f-1b2b-41c4-8165-3ea51b91139e.JPG)
![Map_Sweden_133_Hex_Odd_-30x9](https://user-images.githubusercontent.com/119372/142216029-2527f08a-8511-4d53-8823-f6b587febe15.JPG)
Poland:
![Map_Poland_Default](https://user-images.githubusercontent.com/119372/142216082-207c6fce-8ee6-4451-badb-85deea71ee9d.JPG)
![Map_Poland_133_Hex_Odd_-30x10](https://user-images.githubusercontent.com/119372/142216081-a5e37f09-fe44-478f-9a12-6ca55997e2ac.JPG)
Battlemaps and Scenarios defaulted to a square grid, so no comparison but here are closeups of the new settings:

![Map_Americatown_315_Hex_Row_74x78](https://user-images.githubusercontent.com/119372/142216189-a126bcb1-84aa-40fb-90b3-0d7f7149485b.JPG)
![Map_Battlemap1_500_Hex_Odd_124x-14](https://user-images.githubusercontent.com/119372/142216193-89a974bd-b179-4d91-afe6-fc17b1b3d5ed.JPG)

Also, for the Battlemaps a Scale of 1.0 and 500 Grid size with Hex Col Odd seemed to work well.  I think last night when I was testing I'd nudged them too far so it looked like it was missing parts of the map, but in the video and screenshots there it was 1.0 Scale and 500 Pixels.

Hope this helps!

**Comment by Stefouch** [comment]
Ah! I now see what you are trying to achieve.

Battlemaps have been designed with a smaller grid (smaller than the hexes) on purpose.

As per the rules found on the Player's Manual page 54, hexes on a battlemap are **10-meters** wide. But a human character is usually 1 or 2 meters wide. You can have multiple tokens inside the same hex.

If I had set a grid like you did, drag-and-dropping a token will make it as big as a tree or a house.

Also, I used a square grid because horizontal movement on a hex grid is a bit buggy in Foundry at the moment (V0.8.9).

**Comment by kylania** [comment]
Ahhh, ok that makes sense!

**Comment by illotum** [comment]
In this case, you still need to adjust the scale. Since each square is 10m, the underlying hex is coming up at ~30m, not 10.

**Comment by Kayne** [comment]
If you are ok with almost correct calculating, setting grid scale to 3,33 m works ok-ish. It's not perfect. Or you could leave as it is and always divide by 3 all calculated distances.

**Comment by illotum** [comment]
Indeed. I set it to gridless and a 3m unit. Good enough for me.

**Comment by Stefouch** [comment]
> In this case, you still need to adjust the scale. Since each square is set to 10m, the underlying hex total width is ~30m, not 10. See my initial screenshot.

You are correct 👍 I have to fix in this way!

**Comment by SerotoninRonin** [comment]
![image](https://user-images.githubusercontent.com/95154695/210730074-75a012ad-ecc8-40c0-9631-14a9e1614edd.png)
the current Battlemaps default to 2m hexes which I understand given character occupancy of each 10m hex. The default Grid Size is 108 pixels which means only 4x2m hexes per battlemap hex which makes each battlemap hex 8m not 10m.  Is this intentional?
